name: gtest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install pybind
      run: |
        sudo apt-get install git
        cd ./src
        git clone https://github.com/pybind/pybind11.git
        cd ../
    - name: install gtest manually
      run: |
        sudo apt-get install libgtest-dev 
        cd /usr/src/gtest 
        sudo cmake CMakeLists.txt 
        sudo make 
        sudo cp lib/*.a /usr/lib 
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a 
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: configure
      run: cmake CMakeLists.txt
    - name: make
      run: make
    - name: run Test
      run: ./dl_operations_gtest